#开发环境，后续开发者可以根据实际环境配置环境server:server:
server:
  port: 8088
mybatis:
  type-aliases-package: com.wewin.power_manage.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/power_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 19961127